## roles/ansible-role-redhat-base/handlers/main.yml
# vim:ft=yaml.ansible:
---

- name: restart journald
  service:
    name: systemd-journald
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
...
